<html>
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" type="text/css" href="../../Public/Styles/main.css" />
        <title>$UPERGLOBALS BLOG</title>
    </head>
    <body>
        <header><?php include '__header.phtml' ?></header>
        <h1><?php
             echo $heading;
            ?>
        </h1>
        <p> 
            <?php include $body;?>
        </p>
        <footer><?php include '__footer.phtml'?><footer>
    </body>
</html>