

<form action="login.php" method="post">
  <div>
  <label for="firstname">First name: </label>
  <input name="firstname" type="text"/>
  </div>
    
  <div>
  <label for="lastname">Last name: </label>
  <input name="lastname" type="text"/>
  </div>
    
    <div>
  <label for="username">Username: </label>
  <input name="username" type="text"/>
  </div>

     <div>
  <label for="email">Email: </label>
  <input name="email" type="text"/>
  </div>
    
  <div>
  <label for="password">Password: </label>
  <input name="password" type="password"/>
  </div>
    
  <div>
  <label for="verifypassword">Verify Password: </label>
  <input name="verifypassword" type="password"/>
  </div>
    
 

  <button type="submit">Login</button>
</form>
